web:
  image: alexellis2/nginx-arm:v6
  volumes:
   - ./templates:/etc/nginx/templates
   - ./data:/var/www/html
   - ./config/default:/etc/nginx/sites-available/default
  ports:
   - "8022:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
